"use client";
import { useCallback,useEffect,useState } from "react";
type Mission={id:number;day:number;kind:"code"|"choice"|"photo";tag:string;title:string;task:string;snippet?:string;help?:string;clue?:string;passedAt?:string;choices:string[]};
type State={registered:boolean;player?:{nickname:string;recoveryCode:string};released?:number;completed?:number;total?:number;current?:Mission|null;pendingPhoto?:boolean;missions?:Mission[];nextMidnightMs?:number};
export default function HuntApp(){
 const [state,setState]=useState<State|null>(null),[nickname,setNickname]=useState(""),[recover,setRecover]=useState(""),[answer,setAnswer]=useState(""),[hint,setHint]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[archive,setArchive]=useState(false),[recoveryOpen,setRecoveryOpen]=useState(false),[countdown,setCountdown]=useState(0);
 const load=useCallback(async()=>{const r=await fetch("/api/state",{cache:"no-store"});const data=await r.json();setState(data);setCountdown(data.nextMidnightMs??0)},[]);
 useEffect(()=>{load()},[load]); useEffect(()=>{const timer=setInterval(()=>setCountdown(v=>Math.max(0,v-1000)),1000);return()=>clearInterval(timer)},[]);
 const request=async(url:string,body:unknown)=>{setBusy(true);setError("");const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await r.json();setBusy(false);if(!r.ok){setError(data.error);return false}await load();return true};
 const submitAnswer=async()=>{if(!state?.current)return;const ok=await request("/api/missions/answer",{missionId:state.current.id,answer});if(ok){setNotice("ถอดรหัสสำเร็จ! คำใบ้ถูกบันทึกแล้ว");setAnswer("");setHint(false)}};
 const submitPhoto=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!state?.current)return;const form=new FormData(e.currentTarget);form.set("missionId",String(state.current.id));setBusy(true);setError("");const r=await fetch("/api/missions/photo",{method:"POST",body:form});const data=await r.json();setBusy(false);if(!r.ok){setError(data.error);return}setNotice("ส่งรูปให้นิวตรวจแล้ว");await load()};
 if(!state)return <main className="loading">กำลังเชื่อมต่อระบบ...</main>;
 if(!state.registered)return <main className="onboard"><div className="onboard-card"><div className="brand"><span>&gt;_</span> SENIOR.HUNT</div><p className="eyebrow">PLAYER INITIALIZATION</p><h1>เริ่มภารกิจ<br/><em>ตามหาพี่รหัส</em></h1><p>ไม่ต้องสมัครสมาชิก ใส่เพียงชื่อเล่นเพื่อแยกความคืบหน้าของแต่ละคน</p><input value={nickname} onChange={e=>setNickname(e.target.value)} maxLength={40} placeholder="ชื่อเล่นของน้อง"/><button disabled={busy} onClick={()=>request("/api/player/register",{nickname})}>เริ่มภารกิจ ↗</button><button className="text-btn" onClick={()=>setRecoveryOpen(!recoveryOpen)}>เคยเล่นแล้ว? ใช้รหัสกู้คืน</button>{recoveryOpen&&<div className="recover-row"><input value={recover} onChange={e=>setRecover(e.target.value)} placeholder="รหัส 8 ตัว"/><button onClick={()=>request("/api/player/recover",{code:recover})}>กู้คืน</button></div>}{error&&<p className="error">{error}</p>}</div></main>;
 const current=state.current; const hours=Math.floor(countdown/3600000),mins=Math.floor(countdown%3600000/60000),secs=Math.floor(countdown%60000/1000);
 return <main className="site-shell"><div className="noise"/><nav className="topbar"><div className="brand"><span>&gt;_</span> SENIOR.HUNT</div><div className="player-chip">PLAYER: {state.player?.nickname}</div></nav>
 <section className="dashboard"><aside className="case-panel"><p className="eyebrow">แฟ้มคดีของ {state.player?.nickname}</p><h1>ภารกิจ<br/><em>ตามหาพี่รหัส</em></h1><p className="intro">ภารกิจใหม่เปิดทุกเที่ยงคืน หากพลาดวันไหน ภารกิจเดิมจะรออยู่และต้องทำตามลำดับ</p><div className="case-stats"><div><strong>{String(state.released).padStart(2,"0")}</strong><span>วันที่เปิดแล้ว</span></div><div><strong>{String(state.completed).padStart(2,"0")}</strong><span>ผ่านแล้ว</span></div><div><strong>{state.total}</strong><span>ภารกิจทั้งหมด</span></div></div><button className="recovery-button" onClick={()=>setRecoveryOpen(!recoveryOpen)}>รหัสย้ายเครื่อง / กู้คืน</button>{recoveryOpen&&<div className="recovery-box"><b>{state.player?.recoveryCode}</b><span>เก็บรหัสนี้ไว้เป็นความลับ ใช้เปิดความคืบหน้าในเครื่องใหม่</span></div>}</aside>
 <section className="terminal-card"><div className="terminal-head"><span>DAILY_CLUE.EXE</span><div><i/><i/><i/></div></div><div className="terminal-body"><div className="code-line"><span>01</span><code>status: <b>{current?"ENCRYPTED":"SYNCED"}</b></code></div>{notice&&<p className="success">{notice}</p>}
 {current?<div className="locked-content"><div className="mission-badge">DAY {String(current.day).padStart(2,"0")} · {current.tag}</div><h2>{current.title}</h2><p>{current.task}</p>{current.snippet&&<pre className="challenge-code">{current.snippet}</pre>}{current.kind==="choice"&&<div className="choice-grid">{current.choices.map(c=><button key={c} className={answer===c?"selected":""} onClick={()=>setAnswer(c)}>{c}</button>)}</div>}{current.kind==="code"&&<input className="answer-input" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="พิมพ์คำตอบที่นี่"/>}{current.kind!=="photo"&&<button className="unlock-button" disabled={busy} onClick={submitAnswer}>{busy?"กำลังตรวจ...":"VERIFY & DECRYPT ↗"}</button>}{current.kind==="photo"&&(state.pendingPhoto?<div className="pending-box"><b>รอนิวตรวจรูป</b><span>เมื่ออนุมัติแล้ว ระบบจะปลดล็อกคำใบ้ให้อัตโนมัติ</span><button onClick={load}>ตรวจสอบสถานะอีกครั้ง</button></div>:<form onSubmit={submitPhoto} className="photo-form"><label className="upload-box">เลือกหรือถ่ายรูป<input name="photo" type="file" accept="image/*" capture="user" required/></label><label className="consent"><input type="checkbox" required/> ยินยอมให้นิวดูรูปเพื่อตรวจภารกิจ รูปจะถูกลบภายใน 7 วัน</label><button disabled={busy}>{busy?"กำลังอัปโหลด...":"ส่งรูปให้นิวตรวจ ↗"}</button></form>)}<button className="hint-button" onClick={()=>setHint(!hint)}>{hint?"ซ่อนคำใบ้ช่วย":"ขอคำใบ้ช่วย"}</button>{hint&&<p className="hint">HINT: {current.help}</p>}{error&&<p className="error">{error}</p>}</div>:<div className="caught-up"><span>✓</span><h2>{state.completed===state.total?"ปลดล็อกครบทุกคำใบ้แล้ว":"ทำภารกิจที่เปิดอยู่ครบแล้ว"}</h2><p>{state.completed===state.total?"นำคำใบ้ทั้งหมดไปตามหาพี่รหัสให้เจอ":"ภารกิจถัดไปเปิดใน"}</p>{state.completed!==state.total&&<strong>{String(hours).padStart(2,"0")}:{String(mins).padStart(2,"0")}:{String(secs).padStart(2,"0")}</strong>}</div>}</div></section></section>
 <section className="archive-wrap"><button className="archive-toggle" onClick={()=>setArchive(!archive)}><span>ประวัติคำใบ้และแผนภารกิจ</span><b>{archive?"−":"+"}</b></button>{archive&&<div className="archive-grid">{state.missions?.map(m=><article key={m.id} className={m.passedAt?"available":m.day<=(state.released??0)?"waiting":"future"}><span>DAY {String(m.day).padStart(2,"0")}</span><h3>{m.title}</h3><p>{m.passedAt?m.clue:m.day<=(state.released??0)?"เปิดแล้ว — ต้องผ่านภารกิจก่อนหน้าให้ครบ":"ยังไม่ถึงวันปลดล็อก"}</p></article>)}</div>}</section><footer><span>ระบบติดตามพี่รหัส v2.0</span><a href="/admin">ADMIN</a></footer></main>;
}
