CREATE DATABASE IF NOT EXISTS senior_hunt CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'seniorhunt'@'localhost' IDENTIFIED BY 'CHANGE_THIS_DATABASE_PASSWORD';
GRANT ALL PRIVILEGES ON senior_hunt.* TO 'seniorhunt'@'localhost';
FLUSH PRIVILEGES;
