export type MissionKind = "code" | "choice" | "photo";

export const DEFAULT_MISSIONS = [
  { day: 1, kind: "code", tag: "TRAVEL", title: "เสียงเครื่องยนต์ใกล้ตัว", task: "โค้ดนี้แสดงผลเป็นเลขอะไร?", snippet: "let x = 4;\nx -= 2;\nconsole.log(x);", answer: "2", help: "เริ่มจาก 4 แล้วลบ 2", clue: "พี่เดินทางมามหาวิทยาลัยด้วยมอเตอร์ไซค์", photoPrompt: null },
  { day: 2, kind: "photo", tag: "LOCATION", title: "จุดพักพลัง", task: "ถ่ายรูปให้เห็นใบหน้า พร้อมอาหารหรือเครื่องดื่ม 1 อย่าง และชู 2 นิ้ว", snippet: null, answer: null, help: "ใบหน้า อาหาร/เครื่องดื่ม และสองนิ้วต้องเห็นชัดในภาพเดียว", clue: "ถ้าหาพี่ไม่เจอ ลองมองแถวโรงอาหาร", photoPrompt: "A real person face is visible, food or a drink is visible, and the person is holding up exactly two fingers." },
  { day: 3, kind: "code", tag: "DEVICE", title: "เลขที่อยู่ใกล้มือ", task: "โค้ดนี้แสดงผลเป็นอะไร?", snippet: "console.log([1, 5].join(\"\"));", answer: "15", help: "join ต่อสมาชิกเข้าด้วยกัน ไม่ได้บวกเลข", clue: "โทรศัพท์ของพี่คือ iPhone 15 สีดำ", photoPrompt: null },
  { day: 4, kind: "code", tag: "MAJOR", title: "สองตัวอักษร", task: "โค้ดนี้แสดงผลเป็นอะไร?", snippet: "String.fromCharCode(67, 69)", answer: "CE", help: "67 และ 69 คือรหัสตัวอักษรภาษาอังกฤษ", clue: "พี่เรียนสาขา Computer Engineering (CE)", photoPrompt: null },
  { day: 5, kind: "code", tag: "MUSIC", title: "สิ่งที่มีคอและมีสาย", task: "มีคอแต่ไม่มีหัว มีสายแต่โทรหาใครไม่ได้ เมื่อนิ้วสัมผัสกลับมีเสียง สิ่งนี้คืออะไร?", snippet: null, answer: "กีตาร์", help: "เป็นเครื่องดนตรีชนิดหนึ่ง", clue: "เครื่องดนตรีที่พี่ชอบเล่นคือกีตาร์", photoPrompt: null },
  { day: 6, kind: "photo", tag: "BIRTH", title: "ผู้ร่วมภารกิจพิเศษ", task: "ขออนุญาตอาจารย์ก่อน แล้วถ่ายรูปด้วยกันพร้อมถือกระดาษเขียน DAY 6", snippet: null, answer: null, help: "ต้องเห็นน้อง อาจารย์ และข้อความ DAY 6 ชัดเจน", clue: "พี่เกิดเดือน 12", photoPrompt: "Manual review: student and teacher together with a visible DAY 6 sign." },
  { day: 7, kind: "code", tag: "ARTIST", title: "ชื่อที่สลับด้าน", task: "จัด FU.DT ให้กลับเป็นชื่อที่ถูกต้อง", snippet: "reverse(\"FU.DT\")", answer: "DT.FU", help: "สลับส่วนหน้าและส่วนหลังรอบจุด", clue: "ศิลปินหรือวงที่พี่สนใจคือ DT.FU", photoPrompt: null },
  { day: 8, kind: "choice", tag: "LOGIC", title: "ทิศทางตรงข้าม", task: "คำตรงข้ามของ UP คือข้อใด?", snippet: null, answer: "DOWN", help: "ถ้าไม่ขึ้น ก็ต้องลง", clue: "พี่ใช้โทรศัพท์ iPhone", photoPrompt: null, choices: ["LEFT", "DOWN", "RIGHT"] },
  { day: 9, kind: "photo", tag: "TEAM", title: "ทีมสืบสวนสามคน", task: "ขออนุญาตเพื่อนแล้วถ่ายรูปรวม 3 คน พร้อมชูเลข 1, 2 และ 3 คนละหนึ่งเลข", snippet: null, answer: null, help: "ต้องเห็นทั้งสามคนและเลข 1, 2, 3 ชัดเจนในภาพเดียว", clue: "พี่เรียนสายคอมพิวเตอร์", photoPrompt: "Manual review: three consenting people together, clearly showing the numbers 1, 2, and 3." },
] as const;
